Model Details:
  Organization Name: [Enter the name of the organization of your model (e.g., neuronets, DeepCSR)]
  Basic Information About the Model:
    Person or Organization Developing Model:
    Model Date:
    Model Version:
    Model Type:
    Information About Training Algorithms, Parameters, Fairness Constraints, or Other Applied Approaches, and Features:
    Paper or Other Resource for More Information:
    Citation Details:
    License:
    Where to Send Questions or Comments About the Model:

Intended Use:
  Primary Intended Uses:
  Primary Intended Users:
  Out-of-Scope Use Cases:

Factors:
  Relevant Factors:
  Evaluation Factors:

Metrics:
  Model Performance Measures:
  Decision Thresholds:
  Variation Approaches:

Evaluation Data:
  Datasets:
  Motivation:
  Preprocessing:

Training Data:

  Datasets:
  Motivation:
  Preprocessing:

Quantitative Analyses:

  Unitary Results:
  Intersectional Results:

Ethical Considerations:
  description: [Enter a description of the ethical considerations of your model.]

Caveats and Recommendations:
  description: [Enter a description of the caveats and recommendations of your model.]
