name: ⬆️ Add a new model
description: Add a new model to the nobrainer-zoo
title: "New Model: {org}/{model}/{version}"

body:
  - type: markdown
    attributes:
      value: |
        ## Recommendations to the user:

        :one:. Include a docker folder inside your project which includes the dockerfile and everything associated with it (absolutely recommended).

        :two:. For your prediction script (if applicable), specify path to the best_model (or weights) and 'sample' dataset at the command line using flags.

        :three:. Please avoid absolute paths in any of your scripts. Ideally, relative paths with respect to the root (project) folder is mandatory in the test-command.

        :four:. This issue's title should start with "New Model:" plus your model's org/model/version.

        :five:. All github urls must point to files/folders in the master/main branch of your repository.

        :warning: Please fill all the details of this form to add your model sucessfully to the zoo. Thank you!

        :red_circle: *If the automatic checks fail, this issue will be tagged as 'failed.' However, fix the issues and comment "Ready-for-testing" to test again.
        
  - type: input
    id: path
    attributes:
      label: Model's repository path
      description: Please enter the folder structure for your model {org}/{model}/{version}. 
      placeholder: ex. DeepCSR/deepcsr/1.0
    validations:
      required: true
  - type: input
    id: weights
    attributes:
      label: Best model weights
      description: Please enter the link to the best weights for your model (.pth, .h5, etc). 
      placeholder: Ensure it is available publicly (Google Drive, Onedrive, etc.)
    validations:
      required: true
  - type: input
    id: docker
    attributes:
      label: Docker information
      description: Please enter the link to the docker folder. Following recommendation 1. 
      placeholder: Enter the github link to the docker folder here.
    validations:
      required: true
  - type: textarea
    id: python-scripts
    attributes:
      label: Model's python scripts
      description: Please provide URL's to all your python scripts. It can be a standalone script but could also be a mix of folders and single scripts. 
      placeholder: If multiple URLs please enter one per line.
    validations:
      required: true
  - type: textarea
    id: model_info
    attributes:
      label: Model's card and spec
      description: Please provide a URL for your model_card.yaml and spec.yaml files. For info on creating these files, please see [Docs](https://github.com/neuronets/trained-models/tree/master/docs)
      placeholder: One link per line please.
    validations:
      required: true
  - type: input
    id: sample-data
    attributes:
      label: Sample data
      description: Please provide a link to a sample dataset that can be used to test your model. Must be direct download url.
      placeholder: Enter the sample-dataset here.
    validations:
      required: true
  - type: input
    id: modelConfig
    attributes:
      label: Model config
      description: Please provide a link in github to your model's config file (if applicable).
      placeholder: Enter the config file here.
  - type: textarea
    id: testCommand
    attributes:
      label: Test Command
      description: Please provide read our documentation @root/add_model_instructions.md
      placeholder: Enter your test command.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Read & Followed recommendations
      description: By submitting this issue, you will be sharing your model's data. Therefore, you are ensuring us that you have followed our recommendations.
      options:
        - label: I have read and followed the recommedations in this form and have assigned myself to the issue.
    validations:
      required: true
