name: ⬆️ Add a new model
description: Add a new model to the nobrainer-zoo
title: "New Model: {org}/{model}/{version}"

body:
  - type: markdown
    attributes:
      value: |
        ## Recommendations to the user:

        1. Include a docker folder inside your project which includes the dockerfile and everything associated with it (absolutely recommended).

        2. For your prediction script (if applicable), specify path to the best_model (or weights) and 'sample' dataset at the command line using flags.

        3. Please avoid absolute paths in any of your scripts. Ideally, relative paths with respect to the root (project) folder is mandatory in the test-command.

        4. This issue's title should start with "New Model:" plus our model's org/model/version. You also HAVE to assign yourself to this issue.

        Please fill all the details of this form to add your model sucessfully to the zoo. Thank you!

        *If the automatic checks fail, this issue will be tagged as 'failed.' However, fix the issues and change the label to "Ready-for-testing" to test the checks again.
        
  - type: input
    id: path
    attributes:
      label: Model's repository path
      description: Please enter the folder structure for your model {org}/{model}/{version}. 
      placeholder: ex. DeepCSR/deepcsr/1.0
    validations:
      required: true
  - type: input
    id: weights
    attributes:
      label: Best model weights
      description: Please enter the link to the best weights for your model (.pth, .h5, etc). 
      placeholder: Ensure it is available publicly (Google Drive, Onedrive, etc.)
    validations:
      required: true
  - type: input
    id: docker
    attributes:
      label: Docker information
      description: Please enter the link to the docker folder. Following recommendation 1. 
      placeholder: Enter the github link to the docker folder here.
    validations:
      required: true
  - type: textarea
    id: python-scripts
    attributes:
      label: Model's python scripts
      description: Please provide URL's to all your python scripts. It can be a standalone script but could also be a mix of folders and single scripts. 
      placeholder: If multiple URLs please enter one per line.
    validations:
      required: true
  - type: textarea
    id: model_info
    attributes:
      label: Model's card and spec
      description: Please provide a URL for your model_card.yaml and model_spec.yaml files.
      placeholder: One per line please.
  - type: input
    id: sample-data
    attributes:
      label: Sample data
      description: Please provide a link to a sample dataset that can be used to test your model.
      placeholder: Enter the sample-dataset here.
  - type: input
    id: modelConfig
    attributes:
      label: Model config
      description: Please provide a link in github to your model's config file.
      placeholder: Enter the config file here.
  - type: input
    id: testCommand
    attributes:
      label: Test Command
      description: Please provide a test command for your python script. If any flag has a value that is a path, it is REQUIRED to use relative paths. Relative paths should be referenced within the current repo structure. Weight files are saved to ./<Org>/<model>/<version>/weights/best_model.FILE_FORMAT and Sample Dataset file is saved to ./<Org>/<model>/<version>/example-data/sample.FILE_FORMAT
      placeholder: Enter your test command. i.e python predict.py --model_checkpoint ./DeepCSR/deepcsr/1.0/weights/best_model.pth --dataset ./DeepCSR/deepcsr/1.0/example-data/test.nii.gz --output_dir .
  - type: checkboxes
    id: terms
    attributes:
      label: Read & Followed recommendations
      description: By submitting this issue, you will be sharing your model's data. Therefore, you are ensuring us that you have followed our recommendations.
      options:
        - label: I have read and followed the recommedations in this form and have assigned myself to the issue.
          required: true
