name: ♻️ Update an existing model
description: Update your model
title: "Update Model: {org}/{model}/{version}"
labels: ["update"]

body:
  - type: markdown
    attributes:
      value: |
        ## Recommendations to the user:

  - type: input
    id: path
    attributes:
      label: Model's repository path
      description: Please enter the folder structure for your model {org}/{model}/{version}. 
      placeholder: ex. DeepCSR/deepcsr/1.0
    validations:
      required: true
  - type: input
    id: weights
    attributes:
      label: Update the model's weights
      description: Please enter the link to the best weights for your model (.pth, .h5, etc). 
      placeholder: Ensure it is available publicly (Google Drive, Onedrive, etc.)
    validations:
      required: false
  - type: input
    id: docker
    attributes:
      label: Update Docker information
      description: Please enter the link to the docker folder. Following recommendation 1. 
      placeholder: Enter the github link to the docker folder here.
    validations:
      required: false
  - type: textarea
    id: python-scripts
    attributes:
      label: Update the Model's python scripts
      description: Please provide URL's to all your python scripts. It can be a standalone script but could also be a mix of folders and single scripts. 
      placeholder: If multiple URLs please enter one per line.
    validations:
      required: false
  - type: textarea
    id: model_info
    attributes:
      label: Update the Model's card and spec
      description: Please provide a URL for your model_card.yaml and model_spec.yaml files.
      placeholder: One per line please.
  - type: input
    id: sample-data
    attributes:
      label: Update the Sample dataset
      description: Please provide a link to a sample dataset that can be used to test your model.
      placeholder: Enter the sample-dataset here.
  - type: checkboxes
    id: updates
    attributes:
      label: Select what is being updated
      description: Please select all the checkboxes that apply to this update.
      options:
        - label: Model's weights
          required: false
        - label: Docker information
          required: false
        - label: Model's python scripts
          required: false
        - label: Model's card and spec
          required: false
        - label: Sample dataset
          required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Read & Followed recommendations
      description: By submitting this issue, you will be sharing your model's data. Therefore, you are ensuring us that you have followed our recommendations.
      options:
        - label: I have read and followed the recommedations in this form and have assigned myself to the issue.
          required: true
