image:
  docker: neuronets/nobrainer-zoo:deepcsr
  singularity: /om2/user/egaibor/test_nobrainer/nobrainer-zoo/nobrainerzoo/deepcsr.sif
repository:
  repo_url: None
  committish: None
  repo_download: 'False'
  repo_download_location: None
inference:
  prediction_script: trained-models/DeepCSR/deepcsr/1.0/predict.py
  command: f"python {MODELS_PATH}/{model}/predict.py --conf_path {infile[0]} --model_checkpoint
    {infile[1]} --dataset {infile[2]} --output_dir {infile[3]}"
  data_spec:
    infile:
      n_files: 4
    outfile:
      n_files: null
training_data_info:
  data_number:
    total: null
    train: null
    evaluate: null
    test: null
  biological_sex:
    male: null
    female: null
  age_histogram: null
  race: null
  imaging_contrast_info: null
  dataset_sources: null
  data_sites:
    number_of_sites: null
    sites: null
  scanner_models: null
  hardware: null
  training_parameters:
    input_shape: null
    block_shape: null
    n_classes: null
    lr: null
    n_epochs: null
    total_batch_size: null
    number_of_gpus: null
    loss_function: null
    metrics: null
    data_preprocessing: null
    data_augmentation: null
