name: Add Model

on: [push]
  # push:
    # branches: ["master"]
    
jobs:
  build:
    # created matrix for future os runs
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
        python-version: ["3.9"]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4.2.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          sudo apt-get install datalad
          python -m pip install --upgrade pip
          python -m pip install datalad-osf
          git config --global user.name "trained_models"
          git config --global user.email "trained_models"
      - name: Add model
        env:
          OSF_TOKEN: ${{secrets.OSF_TOKEN}}
        run: |
          datalad siblings
          # datalad push --to origin -d $GITHUB_WORKSPACE
