name: Fetch_Model

on:
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v2
        with:  # no need for the history
          fetch-depth: 1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install datalad
      
      - name: Fetch model file
        run: |
          git annex addurl --relaxed --file <path_to_model/model_name> <google_drive_url>
	  datalad save -m "add model file"
	
