name: Docker build and Push

on:
  pull_request:
    types: [opened, synchronize]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    # Install yaml
    - name: Install yaml
      run: |
          pip install pyyaml

    - name: Get latest model folder
      id: get_latest_folder
      run: |
          python ./.github/workflows/get_latest_model_name.py > latest_folder.txt

    - name: Read latest folder name
      id: read_latest_folder
      run: echo "model_folder=$(cat latest_folder.txt)" >> $GITHUB_ENV
      
    - name: Get Dockerfile path
      id: get_dockerfile_path
      run: |
          python ./.github/workflows/get_dockerfile_path.py > dockerfile_path.txt
      
    - name: Read Dockerfile path
      id: read_dockerfile_path
      run: echo "dockerfile_path=$(cat dockerfile_path.txt)" >> $GITHUB_ENV
      
    - name: Set Docker image name
      id: set_image_name
      run: |
          echo "image_name=neuronets/${{ env.model_folder }}" >> $GITHUB_ENV

    - name: Update yaml file
      id: update_yaml
      run: python ./.github/workflows/update_yaml_info.py

    - name: Generate Model Card
      id: generate_model_card
      run: |
        python ./.github/workflows/create_model_card.py
    
    - name: Commit changes
      run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ${{ env.dockerfile_path }}/spec.yaml ${{ env.dockerfile_path }}/model_card.md
          git commit --amend --no-edit
          git push --force origin HEAD:pull/${{ github.event.pull_request.number }}/merge
