name: Docker build and Push

on:
  pull_request:
    types: [opened, synchronize]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Set pr_body environment variable
      run: echo "pr_body=${{ github.event.pull_request.body }}" >> $GITHUB_ENV
        
    - name: Get latest model folder
      id: get_latest_folder
      run: |
          pip install pyyaml
          python ./.github/workflows/get_latest_model_name.py > latest_folder.txt
      env:
          pr_body: ${{ env.pr_body }}
          
    - name: Read latest folder name
      id: read_latest_folder
      run: echo "model_folder=$(cat latest_folder.txt)" >> $GITHUB_ENV
      
    - name: Get Dockerfile path
      id: get_dockerfile_path
      run: |
          python ./.github/workflows/get_dockerfile_path.py > dockerfile_path.txt
      
    - name: Read Dockerfile path
      id: read_dockerfile_path
      run: echo "dockerfile_path=$(cat dockerfile_path.txt)" >> $GITHUB_ENV
      
    - name: Set Docker image name
      id: set_image_name
      run: |
          echo "image_name=neuronets/${{ env.model_folder }}" >> $GITHUB_ENV


