name: Docker build and Push

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Get latest model folder
      id: get_latest_folder
      run: |
          python get_latest_model_name.py > latest_folder.txt
    
    - name: Read latest folder name
      id: read_latest_folder
      run: echo "model_folder=$(cat latest_folder.txt)" >> $GITHUB_ENV
      
    - name: Get Dockerfile path
      id: get_dockerfile_path
      run: |
          python get_dockerfile_path.py > dockerfile_path.txt
      
    - name: Read Dockerfile path
      id: read_dockerfile_path
      run: echo "dockerfile_path=$(cat dockerfile_path.txt)" >> $GITHUB_ENV
      
    - name: Set Docker image name
      id: set_image_name
      run: |
          echo "image_name=neuronets/${{ steps.read_latest_folder.outputs.model_folder }}" >> $GITHUB_ENV      

    - name: Build and push Docker image
      env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      run: |
          cd ${{ steps.read_dockerfile_path.outputs.dockerfile_path }}
          docker build -t ${{ env.image_name }} .
          docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
          docker push ${{ env.image_name }}
